# -*- coding: utf-8 -*-
"""20127674_LeDucDat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zvo5EyntZddVfj4xwopObjEJgT7rp4N
"""

import unicodedata
import re
import os

encodings = ['ascii','utf-8','utf-16']

vb = input("Nhập đoạn văn bản vào đây: ")
# mystring=list(vb)
email = re.findall(r'\w+@[\w.]+', vb)
# vt1 = email.index(mystring)
# print(vt1)
sdt = re.findall(r'(\d{3}\d{3}\d{4})', vb)
# vt2 = email.index(mystring)
# print(vt2)
print("Email: ", email)
print("Do dai cua chuoi email: ")
print(len(email[0]))
print("SDT: ", sdt)
print("Do dai cua chuoi sdt: ", len(sdt[0]))